// pl/ts/essential-typescript/15-16-standalone-web-app/src/orderDetails.tsx
import { createElement } from './tools/jsxFactory';
import { Product, Order } from './data/entities';

export class OrderDetails {
  props: {
    order: Order;
    cancleCallback: () => void;
    submitCallback: () => void;
  };

  getContent(): HTMLElement {
    return (
      <div>
        <h3 className="text-center bg-primary text-white p-2">Order Summary</h3>
        <div className="p-3">
          <table className="table table-sm table-striped">
            <thead>
              <tr>
                <th>Quantity</th>
                <th>Product</th>
                <th className="text-right">Price</th>
                <th className="text-right">Subtotal</th>
              </tr>
            </thead>
            <tbody>
              {this.props.order.orderLines.map((orderLine) => (
                <tr>
                  <td>{orderLine.quantity}</td>
                  <td>{orderLine.product.name}</td>
                  <td className="text-right">
                    ${orderLine.product.price.toFixed(2)}
                  </td>
                  <td className="text-right">${orderLine.total.toFixed(2)}</td>
                </tr>
              ))}
            </tbody>
            <tfoot>
              <tr>
                <th className="text-right" colSpan="3">
                  Total:
                </th>
                <th className="text-right">
                  ${this.props.order.total.toFixed(2)}
                </th>
              </tr>
            </tfoot>
          </table>
        </div>
        <div className="text-center">
          <button
            className="btn btn-secondary m-1"
            onclick={this.props.cancleCallback}
          >
            Back
          </button>
          <button
            className="btn btn-secondary m-1"
            onclick={this.props.submitCallback}
          >
            Submit Order
          </button>
        </div>
      </div>
    );
  }
}

// pl/ts/essential-typescript/21-22-creating-vue-app/src/views/OrderDetails.vue
<template>
  <div>
    <h3 class="text-center bg-primary text-white p-2">Order Summary</h3>
    <div class="p-3">
      <table class="table table-sm table-striped">
        <thead>
          <tr>
            <th>Quantity</th>
            <th>Product</th>
            <th class="text-right">Price</th>
            <th class="text-right">Subtotal</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="line in order.lines" v-bind:key="line.product.id">
            <td>{{ line.quantity }}</td>
            <td>{{ line.product.name }}</td>
            <td class="text-right">${{ line.product.price.toFixed(2) }}</td>
            <td class="text-right">${{ line.total.toFixed(2) }}</td>
          </tr>
        </tbody>
        <tfoot>
          <tr>
            <th class="text-right" colspan="3">Total:</th>
            <th class="text-right">${{ order.total.toFixed(2) }}</th>
          </tr>
        </tfoot>
      </table>
    </div>
    <div class="text-center">
      <router-link to="/products" class="btn btn-secondary m-1">
        Back
      </router-link>
      <button class="btn btn-primary m-1" @click="submit">Submit Order</button>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { Order } from '@/data/entities';
import { HttpHandler } from '@/data/httpHandler';
import { mapState, mapActions } from 'vuex';
import { StoreState } from '@/store';

export default defineComponent({
  name: 'OrderDetails',
  computed: {
    ...mapState<StoreState>({
      order: (state: StoreState) => state.order,
    }),
  },
  methods: {
    ...mapActions(['storeOrder']),
    submit() {
      this.storeOrder((order: Order) => {
        return new HttpHandler().storeOrder(order).then((id: number) => {
          this.$router.push('/summary');
          return id;
        });
      });
    },
  },
});
</script>
