// pl/ts/essential-typescript/21-22-creating-vue-app/src/components/CategoryList.vue
<template>
  <div>
    <button
      v-for="c in categories"
      v-bind:key="c"
      v-bind:class="getButtonClasses(c)"
      @click="selectCategory(c)"
    >
      {{ c }}
    </button>
  </div>
</template>

<script lang="ts">
import { defineComponent, PropType } from 'vue';

export default defineComponent({
  name: 'CategoryList',
  props: {
    categories: {
      type: Object as PropType<string[]>,
    },
    selected: {
      type: String as PropType<string>,
    },
  },
  methods: {
    selectCategory(category: string) {
      this.$emit('selectCategory', category);
    },
    getButtonClasses(category: string) {
      const btnClass =
        this.selected === category ? 'btn-primary' : 'btn-secondary';
      return `btn btn-block ${btnClass}`;
    },
  },
});
</script>

// pl/ts/essential-typescript/15-16-standalone-web-app/src/categoryList.tsx
import { createElement } from './tools/jsxFactory';

export class CategoryList {
  props: {
    categories: string[];
    selectedCategory: string;
    callback: (selected: string) => void;
  };

  getContent(): HTMLElement {
    return (
      <div>
        {['ALL', ...this.props.categories].map((category) =>
          this.getCategoryButton(category)
        )}
      </div>
    );
  }

  getCategoryButton(category?: string): HTMLElement {
    let selected =
      this.props.selectedCategory === undefined
        ? 'ALL'
        : this.props.selectedCategory;
    let btnClass = selected === category ? 'btn-primary' : 'btn-secondary';
    return (
      <button
        className={`btn btn-block ${btnClass}`}
        onclick={() => this.props.callback(category)}
      >
        {category}
      </button>
    );
  }
}
